apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: devops
spec:
  selector:
    matchLabels:
      app: products
      department: sales
  replicas: 3
  template:
    metadata:
      labels:
        app: products
        department: sales
    spec:
      containers:
      - name: hello
        image: "192.168.0.113:8083/dockerhosted-repo:latest"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: products
    department: sales
  ports:
  - protocol: TCP
    port: 8080 # Service Port
    targetPort: 8080 # Container Port
    nodePort: 31232 # NodePort
